AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  Environment:
    Type: String
    Description: "The environment for the deployment (dev or prod)"
    AllowedValues:
      - dev
      - prod
    Default: dev
    ConstraintDescription: "Must be either 'dev' or 'prod'."
  ApiGatewayId:
    Type: String
    Description: "The API Gateway ID to attach models to"

Resources:
  # ChatMessage Model
  
  ChatMessageModel:
    Type: AWS::ApiGateway::Model
    Properties:
      RestApiId: !Ref ApiGatewayId
      ContentType: application/json
      Name: !Sub "ChatMessage-${Environment}"
      Description: "A single message in the conversation history"
      Schema:
        type: object
        required:
          - role
          - content
        properties:
          role:
            type: string
            enum: [user, assistant]
            description: "The role of the message sender"
          content:
            type: string
            description: "The content of the message"
          timestamp:
            type: string
            format: date-time
            description: "ISO 8601 timestamp of when the message was created"

  # ChatRequest Model

  ChatRequestModel:
    Type: AWS::ApiGateway::Model
    Properties:
      RestApiId: !Ref ApiGatewayId
      ContentType: application/json
      Name: !Sub "ChatRequest-${Environment}"
      Description: "Request body for sending a message to the chat bot"
      Schema:
        type: object
        required:
          - message
        properties:
          message:
            type: string
            description: "The message to send to the chat bot"
            minLength: 1
          history:
            type: array
            description: "Previous conversation history (optional, defaults to empty array)"
            items:
              $ref: "#/definitions/ChatMessage"
            maxItems: 5
          userId:
            type: string
            description: "Optional user identifier for future use"

  # ChatResponse Model

  ChatResponseModel:
    Type: AWS::ApiGateway::Model
    Properties:
      RestApiId: !Ref ApiGatewayId
      ContentType: application/json
      Name: !Sub "ChatResponse-${Environment}"
      Description: "Response from the chat bot"
      Schema:
        type: object
        required:
          - message
          - history
          - timestamp
          - requestId
        properties:
          message:
            type: string
            description: "Tapey's response message"
          history:
            type: array
            description: "Updated conversation history (limited to 5 messages)"
            items:
              $ref: "#/definitions/ChatMessage"
            maxItems: 5
          timestamp:
            type: string
            format: date-time
            description: "ISO 8601 timestamp of when the response was generated"
          requestId:
            type: string
            description: "Unique request identifier for tracking"

  # ErrorResponse Model

  ErrorResponseModel:
    Type: AWS::ApiGateway::Model
    Properties:
      RestApiId: !Ref ApiGatewayId
      ContentType: application/json
      Name: !Sub "ErrorResponse-${Environment}"
      Description: "Error response format"
      Schema:
        type: object
        required:
          - error
          - timestamp
          - requestId
        properties:
          error:
            type: string
            description: "Error message"
          timestamp:
            type: string
            format: date-time
            description: "ISO 8601 timestamp of when the error occurred"
          requestId:
            type: string
            description: "Unique request identifier for tracking"

  # Request Validator

  ChatRequestValidator:
    Type: AWS::ApiGateway::RequestValidator
    Properties:
      RestApiId: !Ref ApiGatewayId
      Name: !Sub "ChatRequestValidator-${Environment}"
      ValidateRequestBody: true
      ValidateRequestParameters: false

Outputs:
  ChatMessageModelName:
    Description: "ChatMessage model name"
    Value: !Ref ChatMessageModel
    Export:
      Name: !Sub "BlockbusterChatBotChatMessageModel-${Environment}"

  ChatRequestModelName:
    Description: "ChatRequest model name"
    Value: !Ref ChatRequestModel
    Export:
      Name: !Sub "BlockbusterChatBotChatRequestModel-${Environment}"

  ChatResponseModelName:
    Description: "ChatResponse model name"
    Value: !Ref ChatResponseModel
    Export:
      Name: !Sub "BlockbusterChatBotChatResponseModel-${Environment}"

  ErrorResponseModelName:
    Description: "ErrorResponse model name"
    Value: !Ref ErrorResponseModel
    Export:
      Name: !Sub "BlockbusterChatBotErrorResponseModel-${Environment}"

  ChatRequestValidatorId:
    Description: "ChatRequestValidator ID"
    Value: !Ref ChatRequestValidator
    Export:
      Name: !Sub "BlockbusterChatBotChatRequestValidator-${Environment}" 