AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  Environment:
    Type: String
    Description: "The environment for the deployment (dev or prod)"
    AllowedValues:
      - dev
      - prod
    Default: dev
    ConstraintDescription: "Must be either 'dev' or 'prod'."
  DomainName:
    Type: String
    Description: "The custom domain name for the API Gateway"
    Default: "api-dev.blockbusterindex.com"
  CertificateArn:
    Type: String
    Description: "ARN of the SSL certificate for the custom domain"

Resources:
  ChatBotApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub "blockbuster-index-chat-bot-api-${Environment}"
      Description: "API Gateway for Blockbuster Index Chat Bot"
      EndpointConfiguration:
        Types:
          - EDGE

  ApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ChatBotApi
      ParentId: !GetAtt ChatBotApi.RootResourceId
      PathPart: "api"

  ChatResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ChatBotApi
      ParentId: !Ref ApiResource
      PathPart: "chat"



  GetChatMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ChatBotApi
      ResourceId: !Ref ChatResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:function:blockbuster-index-chat-bot-${Environment}/invocations"
      MethodResponses:
        - StatusCode: "200"
          ResponseModels:
            application/json: !ImportValue 
              Fn::Sub: "BlockbusterChatBotChatResponseModel-${Environment}"
        - StatusCode: "500"
          ResponseModels:
            application/json: !ImportValue 
              Fn::Sub: "BlockbusterChatBotErrorResponseModel-${Environment}"


  PostChatMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ChatBotApi
      ResourceId: !Ref ChatResource
      HttpMethod: POST
      AuthorizationType: NONE
      RequestModels:
        application/json: !ImportValue 
          Fn::Sub: "BlockbusterChatBotChatRequestModel-${Environment}"
      RequestValidatorId: !ImportValue 
        Fn::Sub: "BlockbusterChatBotChatRequestValidator-${Environment}"
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:function:blockbuster-index-chat-bot-${Environment}/invocations"
      MethodResponses:
        - StatusCode: "200"
          ResponseModels:
            application/json: !ImportValue 
              Fn::Sub: "BlockbusterChatBotChatResponseModel-${Environment}"
        - StatusCode: "400"
          ResponseModels:
            application/json: !ImportValue 
              Fn::Sub: "BlockbusterChatBotErrorResponseModel-${Environment}"
        - StatusCode: "405"
          ResponseModels:
            application/json: !ImportValue 
              Fn::Sub: "BlockbusterChatBotErrorResponseModel-${Environment}"
        - StatusCode: "500"
          ResponseModels:
            application/json: !ImportValue 
              Fn::Sub: "BlockbusterChatBotErrorResponseModel-${Environment}"

  OptionsChatMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ChatBotApi
      ResourceId: !Ref ChatResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        IntegrationResponses:
          - StatusCode: "200"
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'GET,POST,OPTIONS'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            ResponseTemplates:
              application/json: ""
      MethodResponses:
        - StatusCode: "200"
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - GetChatMethod
      - PostChatMethod
      - OptionsChatMethod
    Properties:
      RestApiId: !Ref ChatBotApi
      StageName: !Ref Environment
      Description: !Sub "Deployment for ${Environment} environment"

  CustomDomainName:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName: !Ref DomainName
      RegionalCertificateArn: !Ref CertificateArn
      EndpointConfiguration:
        Types:
          - REGIONAL
      SecurityPolicy: TLS_1_2

  BasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    DependsOn:
      - ApiDeployment
    Properties:
      DomainName: !Ref CustomDomainName
      RestApiId: !Ref ChatBotApi
      Stage: !Ref Environment

  ChatBotUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    DependsOn: ApiDeployment
    Properties:
      UsagePlanName: !Sub "blockbuster-index-chat-bot-usage-plan-${Environment}"
      Description: "Usage plan for Blockbuster Index Chat Bot API with rate limiting"
      Throttle:
        RateLimit: 5
        BurstLimit: 10
      Quota:
        Limit: 1000
        Period: DAY
      ApiStages:
        - ApiId: !Ref ChatBotApi
          Stage: !Ref Environment

Outputs:
  ApiGatewayId:
    Description: "API Gateway ID"
    Value: !Ref ChatBotApi
    Export:
      Name: !Sub "BlockbusterChatBotApiGatewayId-${Environment}"

  ApiGatewayChatResourceId:
    Description: "API Gateway Chat Resource ID"
    Value: !Ref ChatResource
    Export:
      Name: !Sub "BlockbusterChatBotApiGatewayChatResourceId-${Environment}"

  ApiGatewayUrl:
    Description: "API Gateway URL"
    Value: !Sub "https://${ChatBotApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}"
    Export:
      Name: !Sub "BlockbusterChatBotApiUrl-${Environment}"

  CustomDomainUrl:
    Description: "Custom domain URL"
    Value: !Sub "https://${DomainName}/chat"
    Export:
      Name: !Sub "BlockbusterChatBotCustomDomainUrl-${Environment}"

  CustomDomainRegionalDomainName:
    Description: "Regional domain name for the custom domain"
    Value: !GetAtt CustomDomainName.RegionalDomainName
    Export:
      Name: !Sub "BlockbusterChatBotCustomDomainRegionalDomainName-${Environment}"

  CustomDomainRegionalHostedZoneId:
    Description: "Regional hosted zone ID for the custom domain"
    Value: !GetAtt CustomDomainName.RegionalHostedZoneId
    Export:
      Name: !Sub "BlockbusterChatBotCustomDomainRegionalHostedZoneId-${Environment}"
